apiVersion: v1
kind: Service
metadata:
  name: grafana-service # <-- Yeh exact naam aapke Ingress backend se match karta hai
  namespace: monitoring
spec:
  type: ClusterIP # Ingress ke piche hamesha safe production ke liye ClusterIP use hota hai
  selector:
    app: grafana # <-- Yeh deployment ke template label (app: grafana) se connect karega
  ports:
    - protocol: TCP
      port: 3000      # Service ka port jise Ingress hit karega
      targetPort: 3000 # Actual Grafana container ka port
