apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 472
        runAsUser: 472
        runAsGroup: 472
      containers:
        - name: grafana-sc-dashboard
          image: kiwigrid/k8s-sidecar:1.28.0
          imagePullPolicy: IfNotPresent
          env:
            - name: METHOD
              value: WATCH
            - name: LABEL
              value: grafana_dashboard
            - name: FOLDER
              value: /tmp/dashboards
            - name: RESOURCE
              value: configmap
            - name: NAMESPACE
              value: "monitoring"
          volumeMounts:
            - name: sc-dashboard-volume
              mountPath: /tmp/dashboards

        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin123"
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GF_SERVER_PROTOCOL
              value: "https"
            - name: GF_SERVER_CERT_FILE
              value: "/etc/grafana/certs/tls.crt"
            - name: GF_SERVER_CERT_KEY
              value: "/etc/grafana/certs/tls.key"
            - name: GF_SERVER_ROOT_URL
              value: "https://127.0.0.1:3000/"
            - name: GF_DASHBOARDS_ANNOTATION_LIMIT
              value: "100"
            - name: GF_AUTH_GITHUB_ENABLED
              value: "true"
            - name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
              value: "true"
            - name: GF_AUTH_GITHUB_SCOPES
              value: "user:email,read:org"
            - name: GF_AUTH_GITHUB_REDIRECT_URI
              value: "https://127.0.0.1:3000/login/github"
            - name: GF_AUTH_GITHUB_AUTH_URL
              value: "https://github.com/login/oauth/authorize"
            - name: GF_AUTH_GITHUB_TOKEN_URL
              value: "https://github.com/login/oauth/access_token"
            - name: GF_AUTH_GITHUB_API_URL
              value: "https://api.github.com/user"
            - name: GF_AUTH_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: grafana-github-oauth
                  key: client_id
            - name: GF_AUTH_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: grafana-github-oauth
                  key: client_secret
            - name: GF_LOG_LEVEL
              value: "warn"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_ANONYMOUS_ORG_NAME
              value: "Al_NAfi"
            - name: GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH
              value: "/tmp/dashboards/intelligent-observability.json"
          volumeMounts:
            - name: grafana-permanent-storage
              mountPath: /var/lib/grafana
            - name: sc-dashboard-volume
              mountPath: /tmp/dashboards
            - name: tls-certs-volume
              mountPath: /etc/grafana/certs
              readOnly: true
      volumes:
        - name: grafana-permanent-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: sc-dashboard-volume
          emptyDir: {}
        - name: tls-certs-volume
          secret:
            secretName: grafana-tls-secret