apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain # Data delete nahi hoga
  hostPath:
    path: "/mnt/data/jaeger" # Yeh folder aapki Ubuntu machine par khud ban jayega
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: monitoring
spec:
  volumeName: jaeger-pv # Yeh aapke PV ka metadata.name hona chahiye
  storageClassName: "" # Manual PV ke liye isay empty string rakhein
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
