apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 1s
    scrape_configs:
      - job_name: 'python-app'
        static_configs:
          - targets: ['172.17.0.1:8000'] # Ubuntu localhost metrics