apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        args: # <--- Retention Policy
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--query.lookback-delta=5s"
          - "--storage.tsdb.retention.time=30d"
          - "--storage.tsdb.path=/prometheus"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus/
        - name: prometheus-storage # <--- Data folder mount
          mountPath: /prometheus
        - name: rules-volume
          mountPath: /etc/prometheus/rules # Jahan rules save honge
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: prometheus-storage # <--- Local disk storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: rules-volume
        configMap:
          name: prometheus-rules

