apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring
  name: monitoring-viewer
spec:
  rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-monitoring
  namespace: monitoring
subjects:
- kind: User
  name: "dev"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: monitoring-viewer
  apiGroup: rbac.authorization.k8s.io